version: '3.8'
services:
  backend_go:
    build: ./backend_go
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - ./backend_go/.env
    depends_on:
      - mongo
#  backend_nodejs:
#    build: ./backend_nodejs
#    ports:
#      - "5000:5000"
#    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend_go
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
  ml_service:
    build: ./ml_service
    ports:
      - "8001:8001"
    restart: unless-stopped
    env_file:
      - ./ml_service/.env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./feast:/app/feast  # Feast repo is at project root
      - ./feast/data:/app/feast/data
volumes:
  mongo_data: 
  redis_data: