version: '3.8'
services:
  backend_go:
    build: ./backend_go
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - ./backend_go/.env
    depends_on:
      - mongo
#  backend_nodejs:
#    build: ./backend_nodejs
#    ports:
#      - "5000:5000"
#    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend_go
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: 